token: 1bac00ce21474ab6bd1c4c3bbe116396
_core:
  default_config_hash: t5W6QbLZA8s7VAoHDDldhRB2Emm1blOGOOKHMV855Gk
domain_plugin_id: siteimprovedomain_simple
prepublish_enabled: true
api_username: ''
api_key: ''
enabled_content_types:
  article: article
  landing_page: landing_page
  page: page
enabled_taxonomies:
  keywords: keywords
