token: b111dd164537480baec66e67b6d9b423
_core:
  default_config_hash: t5W6QbLZA8s7VAoHDDldhRB2Emm1blOGOOKHMV855Gk
domain_plugin_id: siteimprovedomain_simple
prepublish_enabled: true
api_username: ''
api_key: ''
enabled_content_types:
  article: article
  landing_page: landing_page
  page: page
enabled_taxonomies:
  keywords: keywords
