<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helfi_editorial_form_node_form_alter(&$form, &$form_state, $form_id) {
  $form['actions']['submit']['#submit'][] = 'helfi_editorial_node_form_submit_callback';
}
/**
 * Form submit callback for node forms.
 */
function helfi_editorial_node_form_submit_callback($form, FormStateInterface $form_state) {
  if ($langcode = $form_state->get('langcode')) {
    $language = [
      'language' => \Drupal::languageManager()->getLanguage($langcode)
    ];
    if ($nid = $form_state->get('nid')) {
      $node = [
        'node' => $nid
      ];
      $form_state->setRedirect('entity.node.canonical', $node, $language);
    }
  }
}
